// <auto-generated />
using System;
using Erp.Module.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erp.Module.Core.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erp.Module.Core.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("BankAccount");
                });

            modelBuilder.Entity("Erp.Module.Core.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emirate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDesignatedZone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeZoneEntity")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Erp.Module.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Erp.Module.Core.Entities.BankAccount", b =>
                {
                    b.HasOne("Erp.Module.Core.Entities.Tenant", "Tenant")
                        .WithMany("BankAccounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Erp.Module.Core.Entities.Tenant", b =>
                {
                    b.OwnsOne("Erp.Module.Core.Entities.CorporateTaxSetup", "CorporateTax", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("CorporateTaxTrn")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("CtRegistered")
                                .HasColumnType("bit");

                            b1.Property<DateTime?>("FirstTaxPeriodStart")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("FreeZonePerson")
                                .HasColumnType("bit");

                            b1.Property<bool>("QfzpStatus")
                                .HasColumnType("bit");

                            b1.Property<bool>("SmallBusinessRelief")
                                .HasColumnType("bit");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Erp.Module.Core.Entities.DocumentManagement", "Documents", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EmiratesIdUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MoaUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PassportCopyUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TradeLicenseUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VatCertificateUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Erp.Module.Core.Entities.FinancialSetup", "Financials", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("AccountingMethod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BaseCurrency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("BooksStartDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("FinancialYearStart")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FiscalYear")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReportingCurrency")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Erp.Module.Core.Entities.LocalizationSetup", "Localization", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DateFormat")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("InvoiceLanguage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("OrganizationLanguage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TimeZone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Erp.Module.Core.Entities.SystemControls", "Controls", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("ApprovalWorkflow")
                                .HasColumnType("bit");

                            b1.Property<bool>("AuditTrailEnable")
                                .HasColumnType("bit");

                            b1.Property<bool>("MultiCompanyEnable")
                                .HasColumnType("bit");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Erp.Module.Core.Entities.AddressDetails", "BillingAddress", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AddressLine2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Emirate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FaxNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("POBox")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Erp.Module.Core.Entities.AddressDetails", "RegisteredAddress", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AddressLine2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Emirate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FaxNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("POBox")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("Erp.Module.Core.Entities.VatSetup", "VatDetails", b1 =>
                        {
                            b1.Property<string>("TenantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("FilingFrequency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TrnLabel")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TrnNumber")
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)");

                            b1.Property<bool>("VatRegistered")
                                .HasColumnType("bit");

                            b1.Property<DateTime?>("VatRegistrationDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("VatScheme")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("Controls")
                        .IsRequired();

                    b.Navigation("CorporateTax")
                        .IsRequired();

                    b.Navigation("Documents")
                        .IsRequired();

                    b.Navigation("Financials")
                        .IsRequired();

                    b.Navigation("Localization")
                        .IsRequired();

                    b.Navigation("RegisteredAddress")
                        .IsRequired();

                    b.Navigation("VatDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Erp.Module.Core.Entities.User", b =>
                {
                    b.HasOne("Erp.Module.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Erp.Module.Core.Entities.Tenant", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
